apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'

android {
    namespace 'com.chinalwb.are.demo'
    compileSdk 34
    defaultConfig {
        applicationId "com.chinalwb.are.demo"
        minSdk 21
        targetSdk 34
    }

    buildFeatures {
        viewBinding true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
}

dependencies {
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.google.android.material:material:1.12.0'
    implementation project(':are')
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
}
